name: Pull request

permissions:
  contents: read

on:
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  load-matrix:
    name: Load matrix configuration
    runs-on: ubuntu-latest
    outputs:
      matrix_yaml: ${{ steps.load.outputs.matrix_yaml }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd  # v6.0.2
        with:
          persist-credentials: false
      - name: Load matrix YAML
        id: load
        run: |
          matrix_yaml=$(cat .github/workflows/configs/matrices/test.yml)
          echo "matrix_yaml<<EOF" >> $GITHUB_OUTPUT
          echo "$matrix_yaml" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

  test:
    name: Test
    needs: load-matrix
    uses: ./.github/workflows/execute_matrix.yml
    with:
      name: test
      matrix_yaml_string: ${{ needs.load-matrix.outputs.matrix_yaml }}